photoes:
  source: "/Users/developer/T9/travels/processed"
  export_path: "/Users/developer/T9/workshop/export-photoes-mp4"
  media_mp3_path: "/Users/developer/T9/workshop/media-mp3"
  media_mp3_path_export: "/Users/developer/T9/workshop/media-mp3-export"
  final_photoes_export: "/Users/developer/T9/workshop/final-photoes-mp4"